# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_preferences"
description = "API for resolving preferences"
version = "0.0.1"
categories = ["internationalization"]
license-file = "LICENSE"

authors.workspace = true
edition.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
icu_locale_core = { workspace = true }
tinystr = { workspace = true }

[dev-dependencies]
icu_datetime = { workspace = true }
