# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_plurals"
description = "Unicode Plural Rules categorizer for numeric input"
version = "0.2.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
# Keep this in sync with other crates unless there are exceptions
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "README.md"
]

[package.metadata.cargo-all-features]
skip_optional_dependencies = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
fixed_decimal = { version = "0.2", path = "../../utils/fixed_decimal" }
icu_provider = { version = "0.2", path = "../../provider/core" }
icu_locid = { version = "0.2", path = "../locid" }
serde = { version = "1.0", features = ["derive"], optional = true }
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"
icu = { path = "../icu", default-features = false }
icu_benchmark_macros = { version = "0.2", path = "../../tools/benchmark/macros" }
icu_provider = { version = "0.2", path = "../../provider/core" }
icu_locid = { version = "0.2", path = "../locid" }
icu_locid_macros = { version = "0.2", path = "../locid/macros" }
icu_testdata = { version = "0.2", path = "../../provider/testdata" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[lib]
path = "src/lib.rs"
bench = false  # This option is required for Benchmark CI

[features]
default = ["provider_serde"]
bench = []
provider_serde = ["serde"]

[[bench]]
name = "operands"
harness = false

[[bench]]
name = "parser"
harness = false
required-features = ["provider_serde"]

[[bench]]
name = "pluralrules"
harness = false
required-features = ["provider_serde"]

[[test]]
name = "plurals"
required-features = ["provider_serde"]

[[example]]
name = "unread_emails"
required-features = ["provider_serde"]

[[example]]
name = "elevator_floors"
required-features = ["provider_serde"]
