# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_plurals"
description = "Unicode Plural Rules categorizer for numeric input"
version = "1.2.0"
rust-version = "1.61.0"
authors = ["The ICU4X Project Developers"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
homepage = "https://icu4x.unicode.org"
license = "Unicode-DFS-2016"
categories = ["internationalization"]
# Keep this in sync with other crates unless there are exceptions
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
displaydoc = { version = "0.2.3", default-features = false }
fixed_decimal = { version = "0.5.2", path = "../../utils/fixed_decimal" }
icu_locid = { version = "1.2.0", path = "../locid" }
icu_provider = { version = "1.2.0", path = "../../provider/core", features = ["macros"] }
zerovec = { version = "0.9.4", path = "../../utils/zerovec", features = ["yoke"] }

databake = { version = "0.1.3", path = "../../utils/databake", features = ["derive"], optional = true}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }

icu_plurals_data = { path = "data", optional = true }
icu_locid_transform = { path = "../../components/locid_transform", features = ["data"], optional = true }

[dev-dependencies]
criterion = "0.4"
icu = { path = "../icu" }
icu_benchmark_macros = { path = "../../tools/benchmark/macros" }
icu_provider = { path = "../../provider/core" }
icu_testdata = { path = "../../provider/testdata", default-features = false, features = ["icu_plurals", "icu_locid_transform"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
std = ["fixed_decimal/std", "icu_locid/std", "icu_provider/std"]
serde = ["dep:serde", "zerovec/serde", "icu_locid/serde", "icu_provider/serde"]
datagen = ["serde", "zerovec/databake", "dep:databake"]
experimental = []
bench = ["serde"]
data = ["dep:icu_plurals_data", "dep:icu_locid_transform"]

[lib]
path = "src/lib.rs"
bench = false  # This option is required for Benchmark CI

[package.metadata.cargo-all-features]
# Bench feature gets tested separately and is only relevant for CI
denylist = ["bench"]

[[bench]]
name = "operands"
harness = false

[[bench]]
name = "parser"
harness = false
required-features = ["serde"]

[[bench]]
name = "pluralrules"
harness = false
required-features = ["serde"]

[[test]]
name = "plurals"
required-features = ["serde"]

[[test]]
name = "operands"
required-features = ["serde", "std", "experimental"]

[[test]]
name = "rules"
required-features = ["experimental"]

[[example]]
name = "unread_emails"
required-features = ["serde"]

[[example]]
name = "elevator_floors"
required-features = ["serde"]
