# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "tutorial_harfbuzz"
edition = "2021"
publish = false

[dependencies]
icu_normalizer = { version = "2.0", features = ["harfbuzz_traits", "serde"] }
icu_properties = { version = "2.0", features = ["harfbuzz_traits", "serde"] }
icu_provider = { version = "2.0", features = ["serde"] }
harfbuzz-traits = { version = "0.6.0" }
harfbuzz = { version = "0.6.0" }
