name: icu
version: 0.0.0
repository: https://github.com/unicode-org/icu4x

environment:
  sdk: '>=2.18.0'

dependencies:
  ffi: '>=1.1.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  path: ^1.0.0
