# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).
[package]
name = "icu_provider"
description = "Trait and struct definitions for the ICU data provider"
version = "0.1.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "Cargo.toml",
    "README.md"
]

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
# "serde" is an intentional feature, enabling serialization of HelloWorldV1:
extra_features = ["serde"]

[features]
# Include the ErasedDataProvider, useful for type-agnostic data processing.
# Also required for DataExporter.
erased = []
# Include the SerdeDataProvider, used by the C API.
# Also enables as_serialize() in ErasedDataProvider.
eserde = ["serde", "erased-serde"]

[dependencies]
icu_locid = { version = "0.1", path = "../locid" }
tinystr = "0.4"
writeable = { version = "0.2", path = "../../utils/writeable" }

# For "erased" feature
erased-serde = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"
static_assertions = "1.1"
icu_locid_macros = { version = "0.1", path = "../locid/macros" }
icu_plurals = { version = "0.1", path = "../plurals" }

[[test]]
name = "data_provider"
required-features = ["erased", "serde"]

[[test]]
name = "data_receiver"
required-features = ["eserde"]
