# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_relativetime"
version = "0.1.1"
description = "Relative time formatting"
rust-version = "1.61.0"
authors = ["The ICU4X Project Developers"]
edition = "2021"
repository = "https://github.com/unicode-org/icu4x"
homepage = "https://icu4x.unicode.org"
license = "Unicode-DFS-2016"
categories = ["internationalization"]
# Keep this in sync with other crates unless there are exceptions
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
displaydoc = { version = "0.2.3", default-features = false }
fixed_decimal = { version = "0.5.2", path = "../../utils/fixed_decimal" }
icu_decimal = { version = "1.2.0", path = "../../components/decimal" }
icu_plurals = { version = "1.2.0", path = "../../components/plurals" }
icu_provider = { version = "1.2.0", path = "../../provider/core", features = ["macros"] }
writeable = { version = "0.5.1", path = "../../utils/writeable" }
zerovec = { version = "0.9.4", path = "../../utils/zerovec", features = ["yoke"] }

databake = { version = "0.1.3", path = "../../utils/databake", features = ["derive"], optional = true}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }

icu_relativetime_data = { path = "data", optional = true }
icu_locid_transform = { path = "../../components/locid_transform", features = ["data"], optional = true }

[dev-dependencies]
icu = { path = "../../components/icu", features = ["icu_relativetime"] }

[features]
std = ["fixed_decimal/std", "icu_decimal/std", "icu_plurals/std", "icu_provider/std"]
serde = ["dep:serde", "zerovec/serde", "icu_provider/serde", "icu_plurals/serde", "icu_decimal/serde"]
datagen = ["std", "serde", "dep:databake", "zerovec/databake"]
data = ["dep:icu_relativetime_data", "dep:icu_locid_transform", "icu_decimal/data", "icu_plurals/data"]

[[test]]
name = "tests"
path = "tests/tests.rs"
