# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_ffi_coverage"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
diplomat_core = { git = "https://github.com/rust-diplomat/diplomat", rev = "8d125999893fedfdf30595e97334c21ec4b18da9" }
elsa = "1"
lazy_static ="1"
rustdoc-types = "0.17"
serde_json = "1"
syn-inline-mod = "0.6.0"

