# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

# This is a cargo-make file included in the toplevel Makefile.toml

[tasks.testdata-download]
description = "Download fresh CLDR JSON, overwriting the existing CLDR JSON."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-testdata-download",
    "--",
    "-v",
]

[tasks.icu4x-key-extract]
description = "Build and smoke-test the icu4x-key-extract tool"
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-key-extract",
    "--",
    "--help",
]

[tasks.testdata-build-json]
description = "Build ICU4X JSON from the downloaded CLDR JSON, overwriting the existing ICU4X JSON."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--",
    "--input-from-testdata",
    "--out-testdata",
    "--test-keys",
    "--test-locales",
    "--syntax=json",
    "--pretty",
    "--overwrite",
]

[tasks.testdata-build-blob]
description = "Build ICU4X data as a Bincode blob, overwriting the existing Bincode blob."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--",
    "--format=blob",
    "--input-from-testdata",
    "--out-testdata",
    "--test-keys",
    "--test-locales",
    "--overwrite",
]

[tasks.testdata-build-blob-smaller]
description = "Build a small subset of ICU4X data as a Postcard blob."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--",
    "--format=blob",
    "--input-from-testdata",
    "--out=provider/testdata/data/decimal-bn-en.postcard",
    "--keys=decimal/symbols@1",
    "--locales=bn",
    "--locales=en",
    "--overwrite",
]

[tasks.testdata-build-worklog-json]
description = "Build JSON files for the work_log example"
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--",
    "--input-from-testdata",
    "--out=tools/datagen/tests/testdata/work_log_json",
    "--key-file=tools/datagen/tests/testdata/work_log+keys.txt",
    "--locales=de",
    "--locales=es",
    "--overwrite",
]

[tasks.testdata]
description = "Rebuild all ICU4X testdata from source data checked into the repository"
category = "ICU4X Data"
dependencies = [
    "testdata-build-json",
    "testdata-build-blob",
    "testdata-build-blob-smaller",
    "testdata-build-worklog-json",
]

[tasks.testdata-check]
description = "Rebuild ICU4X testdata and ensure that the working copy is clean"
category = "ICU4X Data"
dependencies = [
    "testdata"
]
script_runner = "@duckscript"
script = '''
exit_on_error true

output = exec git status --porcelain=v1 provider/testdata/data
output_length = length ${output.stdout}
if greater_than ${output_length} 0
    msg = array "" ""
    array_push ${msg} "Test data needs to be updated. Please run `cargo make testdata`:"
    array_push ${msg} ""
    array_push ${msg} "${output.stdout}"
    msg = array_join ${msg} "\n"
    trigger_error ${msg}
end
'''

[tasks.testdata-build-bincode]
description = "Build ICU4X Bincode filesystem structure from the downloaded CLDR JSON, overwriting the existing ICU4X Bincode if present."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--",
    "--input-from-testdata",
    "--out-testdata",
    "--test-keys",
    "--test-locales",
    "--syntax=bincode",
    "--overwrite",
]

[tasks.testdata-build-bincode-all]
description = "Build ICU4X Bincode filesystem structure from the downloaded CLDR JSON, testing all available locales, and overwriting the existing ICU4X Bincode if present."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--",
    "--input-from-testdata",
    "--out-testdata",
    "--test-keys",
    "--all-locales",
    "--syntax=bincode",
    "--overwrite",
]
