# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "download-repo-sources"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
crlify = { workspace = true }
icu_provider_source = { workspace = true }
icu_locale_core = { workspace = true, features = ["databake"] }
icu_provider = { workspace = true }

clap = { workspace = true, features = ["derive"] }
eyre = { workspace = true }
flate2 = { workspace = true }
log = { workspace = true }
simple_logger = { workspace = true }
ureq = { workspace = true }
tar = { workspace = true }
zip = { workspace = true, features = ["deflate"] }

[package.metadata.cargo-all-features]
# Unpublished internal tool; skip
skip_package = true
