# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "zerotrie"
description = "A data structure that efficiently maps strings to integers"
version = "0.0.0"

rust-version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license-file.workspace = true
categories.workspace = true
include.workspace = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
# Bench feature gets tested separately and is only relevant for CI
denylist = ["bench"]

[dependencies]
displaydoc = { version = "0.2.3", default-features = false }
litemap = { workspace = true, features = ["alloc"], optional = true }
serde = { version = "1.0", optional = true }
zerovec = { workspace = true, optional = true }

[dev-dependencies]
bincode = "1.0"
icu_benchmark_macros = { workspace = true }
litemap = { workspace = true }
postcard = { version = "1.0", default-features = false, features = ["alloc"] }
rand = "0.8"
rand_pcg = "0.3"
serde = { version = "1.0", default-features = false }
serde_json = "1.0"
zerovec = { workspace = true, features = ["serde", "hashmap"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.4"

[lib]
bench = false  # This option is required for Benchmark CI

[features]
default = []
bench = ["litemap"]
alloc = []
litemap = ["dep:litemap", "alloc"]
serde = ["dep:serde", "dep:litemap", "alloc", "litemap/serde", "zerovec?/serde"]

[[bench]]
name = "overview"
harness = false

[[test]]
name = "builder_test"
required-features = ["alloc", "litemap"]
