# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

##########################################
# PLEASE KEEP THIS IN SYNC WITH cargo.md #
##########################################

[package]
name = "tutorial_baked"
edition = "2021"
publish = false

[dependencies]
icu = { version = "2.0.0", default-features = false } # turn off compiled_data
icu_provider = { version = "2.0.0", features = ["baked"] } # for databake
zerovec = "0.11.3-dev" # for databake

[build-dependencies]
icu = "2.0.0"
icu_provider_export = "2.0.0"
icu_provider_source = "2.0.0"
