# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

# This crate is slated for deletion. It is kept around to keep the crates tutorials working,
# as published 1.2 doesn't compile with local code due to changes in provider modules.

[package]
name = "icu_testdata"
description = "Pre-built test data for ICU4X"
version = "1.2.0"
publish = false

[dependencies]
icu_calendar = "1.2.0"
icu_datetime = "1.2.0"
icu_decimal = "1.2.0"
icu_displaynames = { version = "0.10", optional = true }
icu_list = "1.2.0"
icu_locid_transform = "1.2.0"
icu_plurals = "1.2.0"
icu_provider = { version = "1.2.0" }
zerovec = { version = "0.9.4" }
