# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_host_info"
version = "0.1.0"
publish = false

rust-version = "1.83"
authors = ["The ICU4X Project Developers"]
edition = "2021"
repository = "https://github.com/unicode-org/icu4x"
homepage = "https://icu4x.unicode.org"
license = "Unicode-3.0"
categories = ["internationalization"]
include = [
    "data/**/*",
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "build.rs",
]

[dependencies]
displaydoc = { version = "0.2.3", default-features = false }
icu_locale_core = { version = "2.1.0", path = "../../components/locale_core", features = ["alloc"] }
icu_datetime = { version = "2.1.0", path = "../../components/datetime", optional = true }
libc = "0.2.175"

[target.'cfg(target_os = "linux")'.dependencies]
gio = { version = "0.21.2", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = { version = "0.8.6" }
core-foundation = { version = "0.10.1" }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.62"
features = [
    "System",
    "Foundation",
    "System_UserProfile",
    "Foundation_Collections",
    "Globalization",
    "Globalization_DateTimeFormatting",
    "Win32",
    "Win32_Globalization",
]

[dev-dependencies]
icu = { path = "../../components/icu", default-features = false }
icu_datetime = { version = "2.1.0", path = "../../components/datetime", features = ["compiled_data"] }
icu_calendar = { version = "2.1.0", path = "../../components/calendar" }
icu_time = { version = "2.1.0", path = "../../components/time", features = ["compiled_data"] }

[features]
default = []
datetime = ["dep:icu_datetime"]
gnome = ["dep:gio"]

[[example]]
name = "dt_format"
required-features = ["datetime"]

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
