# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_host_info"
version = "0.1.0"
publish = false

rust-version = "1.82"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true
include.workspace = true

[dependencies]
displaydoc = { workspace = true }
icu_locale_core = { workspace = true, features = ["alloc"] }
icu_datetime = { workspace = true, optional = true }
libc = "0.2.175"

[target.'cfg(target_os = "linux")'.dependencies]
gio = { version = "0.21.2", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = { version = "0.8.6" }
core-foundation = { version = "0.10.1" }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.60.0"
features = [
    "System",
    "Foundation",
    "System_UserProfile",
    "Foundation_Collections",
    "Globalization",
    "Globalization_DateTimeFormatting",
    "Win32",
    "Win32_Globalization",
]

[dev-dependencies]
icu = { path = "../../components/icu", default-features = false }
icu_datetime = { workspace = true, features = ["compiled_data"] }
icu_calendar = { workspace = true }
icu_time = { workspace = true, features = ["compiled_data"] }

[features]
default = []
datetime = ["dep:icu_datetime"]
gnome = ["dep:gio"]

[[example]]
name = "dt_format"
required-features = ["datetime"]

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
