# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "zerofrom-derive"
description = "Custom derive for the zerofrom crate"
version = "0.1.2"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
categories = ["data-structures", "memory-management", "caching", "no-std"]
keywords = ["zerocopy", "serialization", "lifetime", "borrow"]

edition.workspace = true
license-file.workspace = true
repository.workspace = true

[package.metadata.workspaces]
independent = true

[lib]
proc_macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "2", features = ["derive", "fold", "visit"] }
synstructure = "0.13"

[dev-dependencies]
zerofrom = { workspace = true, features = ["derive"]}
zerovec = { workspace = true, features = ["yoke"] }

