name: icu
repository: https://github.com/unicode-org/icu4x

publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  code_assets: ^0.19.4
  ffi: ^2.0.0
  hooks: ^0.19.5
  meta: ^1.16.0

dev_dependencies:
  args: ^2.6.0
  lints: ^5.1.1
  test: ^1.21.0
  path: ^1.0.0
