name: icu4x
description: > 
  Dart bindings for the Rust icu4x crate.
version: 2.0.0-dev.0
repository: https://github.com/unicode-org/icu4x/tree/main/ffi/dart
issue_tracker: https://github.com/unicode-org/icu4x/issues?q=is%3Aissue%20is%3Aopen%20label%3AU-flutter

platforms:
  # web: Not supported for now.
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - i18n

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  args: ^2.7.0
  code_assets: ^0.19.5
  collection: ^1.19.1
  crypto: ^3.0.6
  ffi: ^2.0.0
  hooks: ^0.20.0
  logging: ^1.3.0
  meta: ^1.16.0
  native_toolchain_c: ^0.17.1
  path: ^1.9.1
  record_use: ^0.4.1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  test: ^1.21.0

hooks:
  user_defines:
    icu4x:
      buildMode: checkout
      checkoutPath: ../../
