# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

name: icu4x
description: > 
  Dart bindings for the Rust `icu` internationalization crate.
version: 2.1.0-dev.0
repository: https://github.com/unicode-org/icu4x/tree/main/ffi/dart
issue_tracker: https://github.com/unicode-org/icu4x/issues?q=is%3Aissue%20is%3Aopen%20label%3AU-flutter

platforms:
  # web: Not supported for now.
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - i18n

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  args: ^2.7.0
  code_assets: ^0.19.10
  collection: ^1.19.1
  crypto: ^3.0.7
  ffi: ^2.1.4
  # Pinned as we use unstable APIs
  hooks: '>=0.20.4 <0.20.5'
  logging: ^1.3.0
  meta: ^1.17.0
  native_toolchain_c: ^0.17.2
  path: ^1.9.1
  record_use: ^0.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0

hooks:
  user_defines:
    icu4x:
      buildMode: checkout
      checkoutPath: ../../
