# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_collator"
description = "API for comparing strings according to language-dependent conventions"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
[package.metadata.docs.rs]
all-features = true

[dependencies]
displaydoc = { workspace = true }
icu_collections = { workspace = true }
icu_normalizer = { workspace = true }
icu_locale_core = { workspace = true }
icu_properties = { workspace = true }
icu_provider = { workspace = true, features = ["macros"] }
utf8_iter = { workspace = true }
utf16_iter = { workspace = true }
smallvec = { workspace = true, features = ["union", "const_generics", "const_new"] }
zerovec = { workspace = true }

databake = { workspace = true, optional = true, features = ["derive"] }
serde = { workspace = true, features = ["derive", "alloc"], optional = true }

icu_collator_data = { workspace = true, optional = true }

[dev-dependencies]
arraystring = { workspace = true }
atoi = { workspace = true }
icu = { path = "../../components/icu", default-features = false }
icu_locale_core = { path = "../../components/locale_core" }
icu_provider_adapters = { path = "../../provider/adapters" }
icu_normalizer_data = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true }

[features]
default = ["compiled_data"]
std = ["icu_collections/std", "icu_locale_core/std", "icu_normalizer/std", "icu_properties/std", "icu_provider/std"]
serde = ["dep:serde", "zerovec/serde", "icu_properties/serde", "icu_normalizer/serde", "icu_collections/serde", "icu_provider/serde"]
datagen = ["serde", "dep:databake", "zerovec/databake", "icu_properties/datagen", "icu_normalizer/datagen", "icu_collections/databake"]
compiled_data = ["dep:icu_collator_data", "icu_normalizer/compiled_data"]

[[bench]]
name = "bench"
harness = false
