# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "tutorials-test"
publish = false
version = "0.0.0"
edition = "2021"

[dev-dependencies]
databake = { version = "0.1", features = ["derive"] }
displaydoc = "0.2.3"
icu = "1.2"
icu_datagen = { version = "1.2", default-features = false}
icu_provider = { version = "1.2", features = ["deserialize_json"] }
icu_provider_adapters = { version = "1.2", features = ["serde"] }
icu_provider_blob = "1.2"
icu_provider_fs = "1.2"
icu_testdata = "1.2"
itertools = "0.10"
litemap = "0.7"
lru = "0.8.1"
serde = { version = "1.0", features = ["derive", "alloc", "std"] }
serde-aux = "4.1.2"
tinystr = { version = "0.7", features = ["alloc"], default-features = false }
writeable = { version = "0.5" }
yoke = { version = "0.7" }
zerofrom = { version = "0.1" }
