# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[patch.crates-io]
icu_calendar = { path = "../../components/calendar" }
icu_calendar_data = { path = "../../components/calendar/data" }
icu_collator = { path = "../../components/collator" }
icu_collator_data = { path = "../../components/collator/data" }
icu_collections = { path = "../../components/collections" }
icu_codepointtrie_builder = { path = "../../components/collections/codepointtrie_builder" }
icu_datetime = { path = "../../components/datetime" }
icu_datetime_data = { path = "../../components/datetime/data" }
icu_decimal = { path = "../../components/decimal" }
icu_decimal_data = { path = "../../components/decimal/data" }
icu = { path = "../../components/icu" }
icu_list = { path = "../../components/list" }
icu_list_data = { path = "../../components/list/data" }
icu_locid_transform = { path = "../../components/locid_transform" }
icu_locid_transform_data = { path = "../../components/locid_transform/data" }
icu_locid = { path = "../../components/locid" }
icu_normalizer = { path = "../../components/normalizer" }
icu_normalizer_data = { path = "../../components/normalizer/data" }
icu_plurals = { path = "../../components/plurals" }
icu_plurals_data = { path = "../../components/plurals/data" }
icu_properties = { path = "../../components/properties" }
icu_properties_data = { path = "../../components/properties/data" }
icu_segmenter = { path = "../../components/segmenter" }
icu_segmenter_data = { path = "../../components/segmenter/data" }
icu_timezone = { path = "../../components/timezone" }
icu_timezone_data = { path = "../../components/timezone/data" }
bies = { path = "../../experimental/bies" }
icu_casemap = { path = "../../experimental/casemap" }
icu_casemap_data = { path = "../../experimental/casemap/data" }
icu_compactdecimal = { path = "../../experimental/compactdecimal" }
icu_compactdecimal_data = { path = "../../experimental/compactdecimal/data" }
icu_displaynames = { path = "../../experimental/displaynames" }
icu_displaynames_data = { path = "../../experimental/displaynames/data" }
icu_harfbuzz = { path = "../../experimental/harfbuzz" }
ixdtf = { path = "../../experimental/ixdtf" }
icu_relativetime = { path = "../../experimental/relativetime" }
icu_relativetime_data = { path = "../../experimental/relativetime/data" }
icu_unicodeset_parser = { path = "../../experimental/unicodeset_parser" }
icu_capi_cdylib = { path = "../../ffi/capi_cdylib" }
icu_capi_staticlib = { path = "../../ffi/capi_staticlib" }
icu_capi = { path = "../../ffi/diplomat" }
icu4x_ecma402 = { path = "../../ffi/ecma402" }
icu_freertos = { path = "../../ffi/freertos" }
icu_provider_adapters = { path = "../../provider/adapters" }
icu_provider_blob = { path = "../../provider/blob" }
icu_provider = { path = "../../provider/core" }
icu_datagen = { path = "../../provider/datagen" }
icu_provider_fs = { path = "../../provider/fs" }
icu_provider_macros = { path = "../../provider/macros" }
databake = { path = "../../utils/databake" }
databake-derive = { path = "../../utils/databake/derive" }
deduplicating_array = { path = "../../utils/deduplicating_array" }
fixed_decimal = { path = "../../utils/fixed_decimal" }
litemap = { path = "../../utils/litemap" }
icu_pattern = { path = "../../utils/pattern" }
tinystr = { path = "../../utils/tinystr" }
tzif = { path = "../../utils/tzif" }
writeable = { path = "../../utils/writeable" }
yoke = { path = "../../utils/yoke" }
yoke-derive = { path = "../../utils/yoke/derive" }
zerofrom = { path = "../../utils/zerofrom" }
zerofrom-derive = { path = "../../utils/zerofrom/derive" }
zerovec = { path = "../../utils/zerovec" }
zerovec-derive = { path = "../../utils/zerovec/derive" }
