# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "yoke"
version = "0.7.1"
description = "Abstraction allowing borrowed data to be carried along with the backing data it borrows from"
rust-version = "1.61.0"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
edition = "2021"
repository = "https://github.com/unicode-org/icu4x"
license = "Unicode-DFS-2016"
categories = ["data-structures", "memory-management", "caching", "no-std"]
keywords = ["zerocopy", "serialization", "lifetime", "borrow", "self-referential"]
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[package.metadata.workspaces]
independent = true

[features]
derive = ["dep:yoke-derive", "zerofrom/derive"]
alloc = ["stable_deref_trait/alloc", "serde?/alloc", "zerofrom/alloc"]
default = ["alloc", "zerofrom"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
stable_deref_trait = { version = "1.2.0", default-features = false }

yoke-derive = { version = "0.7.0", path = "./derive", optional = true }

serde = { version = "1.0", default-features = false, optional = true }
zerofrom = { version = "0.1.1", path = "../zerofrom", default-features = false, optional = true} 

[dev-dependencies]
bincode = "1.3.3"
serde = "1.0.125"
