# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "yoke"
version = "0.5.0"
description = "Abstraction allowing borrowed data to be carried along with the backing data it borrows from"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]
edition = "2018"
repository = "https://github.com/unicode-org/icu4x"
license-file = "LICENSE"
categories = ["data-structures", "memory-management", "caching", "no-std"]
keywords = ["zerocopy", "serialization", "lifetime", "borrow", "self-referential"]
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[features]
derive = ["yoke-derive", "zerofrom/derive"]
alloc = ["stable_deref_trait/alloc", "serde/alloc", "zerofrom/alloc"]
default = ["alloc", "zerofrom"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
stable_deref_trait = { version = "1.2.0", features = ["alloc"], default-features = false }
serde = { version = "1.0", optional = true, default-features = false }
yoke-derive = { path = "./derive", version = "0.5.0", optional = true }
zerofrom = { path = "../zerofrom", version = "0.1.0", default-features = false, optional = true} 

[dev-dependencies]
bincode = "1.3.3"
serde = "1.0.125"
