# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_time"
description = "API for resolving and manipulating time zone information"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
calendrical_calculations = { workspace = true }
displaydoc = { workspace = true }
icu_calendar = { workspace = true }
icu_provider = { workspace = true }
ixdtf = { workspace = true, optional = true }
tinystr = { workspace = true, features = ["zerovec"] }
zerotrie = { workspace = true, features = ["yoke", "zerofrom"] }
zerovec = { workspace = true, features = ["derive", "yoke"] }
writeable = { workspace = true }

databake = { workspace = true, optional = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }

icu_time_data = { workspace = true, optional = true }

[dev-dependencies]
icu = { path = "../../components/icu", default-features = false }

[features]
default = ["compiled_data", "ixdtf"]
ixdtf = ["dep:ixdtf", "icu_calendar/ixdtf"]
serde = ["dep:serde", "zerovec/serde", "zerotrie/serde", "tinystr/serde", "icu_provider/serde"]
datagen = ["serde", "dep:databake", "zerovec/databake", "zerotrie/databake", "tinystr/databake"]
compiled_data = ["dep:icu_time_data", "icu_calendar/compiled_data"]
alloc = ["tinystr/alloc", "zerotrie/alloc", "serde?/alloc"]