# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "ixdtf"
description = "Parser for Internet eXtended DateTime Format"
version = "0.6.4"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version = "1.82"

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["duration"]
duration = []

[dependencies]

[dev-dependencies]
serde-json-core = { workspace = true, features = ["std"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true }

[package.metadata.cargo-semver-checks.lints]
workspace = true
