# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_provider_adapters"
description = "Adapters for composing and manipulating data providers."
version = "1.2.0"
rust-version = "1.61.0"
authors = ["The ICU4X Project Developers"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
homepage = "https://icu4x.unicode.org"
license = "Unicode-DFS-2016"
categories = ["internationalization"]
# Keep this in sync with other crates unless there are exceptions
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[dependencies]
icu_locid = { version = "1.2.0", path = "../../components/locid", features = ["zerovec"] }
icu_locid_transform = { version = "1.2.0", path = "../../components/locid_transform" }
icu_provider = { version = "1.2.0", path = "../core", features = ["macros"] }
tinystr = { version = "0.7.1", path = "../../utils/tinystr", features = ["zerovec"] }
yoke = { version = "0.7.1", path = "../../utils/yoke" }
zerovec = { version = "0.9.4", path = "../../utils/zerovec", features = ["yoke"] }

databake = { version = "0.1.3", path = "../../utils/databake", features = ["derive"], optional = true}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }

[dev-dependencies]
icu_provider = { path = "../core", features = ["macros", "deserialize_json"] }
icu_provider_fs = { path = "../fs" }
icu_testdata = { path = "../testdata", default-features = false, features = ["buffer"] }
writeable = { path = "../../utils/writeable" }

[features]
std = ["icu_locid/std", "icu_provider/std"]
serde = ["dep:serde", "zerovec/serde", "icu_locid/serde", "icu_locid_transform/serde", "icu_provider/serde"]
datagen = ["std", "serde", "icu_provider/datagen"]
