# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_provider_adapters"
description = "Adapters for composing and manipulating data providers."
license = "Unicode-3.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
icu_locale = { workspace = true }
icu_provider = { workspace = true, features = ["macros"] }
tinystr = { workspace = true, features = ["zerovec"] }
zerovec = { workspace = true, features = ["yoke"] }

databake = { workspace = true, features = ["derive"], optional = true}
serde = { workspace = true, features = ["derive", "alloc"], optional = true }

[dev-dependencies]
icu = { path = "../../components/icu" }
icu_provider = { path = "../../provider/core", features = ["macros", "deserialize_json"] }
icu_provider_fs = { path = "../../provider/fs" }
icu_provider_blob = { path = "../../provider/blob" }
icu_locale = { path = "../../components/locale" }
writeable = { path = "../../utils/writeable" }

[features]
std = ["icu_provider/std"]
serde = ["dep:serde", "zerovec/serde", "icu_locale/serde", "icu_provider/serde"]
datagen = ["std", "serde", "icu_provider/datagen"]
