# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

# All code in tutorials is built outside the workspace, as a client would.
# In order to test with repo code, this config.toml is used automatically
# by cargo for any invocation inside docs/tutorials/.

[patch.crates-io]
# KEEP IN SYNC WITH TOP-LEVEL Cargo.toml

# Components
icu = { path = "../../components/icu" }
icu_calendar = { path = "../../components/calendar" }
icu_casemap = { path = "../../components/casemap" }
icu_collator = { path = "../../components/collator" }
icu_collections = { path = "../../components/collections" }
icu_codepointtrie_builder = { path = "../../components/collections/codepointtrie_builder" }
icu_datetime = { path = "../../components/datetime" }
icu_decimal = { path = "../../components/decimal" }
icu_list = { path = "../../components/list" }
icu_locid = { path = "../../components/locid" }
icu_locid_transform = { path = "../../components/locid_transform" }
icu_normalizer = { path = "../../components/normalizer" }
icu_plurals = { path = "../../components/plurals" }
icu_properties = { path = "../../components/properties" }
icu_segmenter = { path = "../../components/segmenter" }
icu_timezone = { path = "../../components/timezone" }
icu_experimental = { path = "../../experimental/components" }
icu_unitsconversion = { path = "../../experimental/unitsconversion" }

# FFI
icu_capi = { path = "../../ffi/capi" }
icu_freertos = { path = "../../ffi/freertos" }
icu4x_ecma402 = { path = "../../experimental/ecma402" }
icu_harfbuzz = { path = "../../experimental/harfbuzz" }

# Provider
icu_datagen = { path = "../../provider/datagen" }
icu_provider = { path = "../../provider/core" }
icu_provider_adapters = { path = "../../provider/adapters" }
icu_provider_blob = { path = "../../provider/blob" }
icu_provider_fs = { path = "../../provider/fs/" }
icu_provider_macros = { path = "../../provider/macros" }

# Baked data
icu_calendar_data = { path = "../../provider/baked/calendar" }
icu_casemap_data = { path = "../../provider/baked/casemap" }
icu_collator_data = { path = "../../provider/baked/collator" }
icu_datetime_data = { path = "../../provider/baked/datetime" }
icu_decimal_data = { path = "../../provider/baked/decimal" }
icu_experimental_data = { path = "../../provider/baked/experimental" }
icu_list_data = { path = "../../provider/baked/list" }
icu_locid_transform_data = { path = "../../provider/baked/locid_transform" }
icu_normalizer_data = { path = "../../provider/baked/normalizer" }
icu_personnames_data = { path = "../../experimental/personnames/data" }
icu_plurals_data = { path = "../../provider/baked/plurals" }
icu_properties_data = { path = "../../provider/baked/properties"}
icu_segmenter_data = { path = "../../provider/baked/segmenter" }
icu_timezone_data = { path = "../../provider/baked/timezone" }

crlify = { path = "../../utils/crlify" }
databake = { path = "../../utils/databake" }
databake-derive = { path = "../../utils/databake/derive" }
deduplicating_array = { path = "../../utils/deduplicating_array" }
fixed_decimal = { path = "../../utils/fixed_decimal" }
litemap = { path = "../../utils/litemap" }
icu_pattern = { path = "../../utils/pattern" }
tinystr = { path = "../../utils/tinystr" }
tzif = { path = "../../utils/tzif" }
writeable = { path = "../../utils/writeable/" }
yoke = { path = "../../utils/yoke" }
yoke-derive = { path = "../../utils/yoke/derive" }
zerofrom = { path = "../../utils/zerofrom" }
zerofrom-derive = { path = "../../utils/zerofrom/derive" }
zerovec = { path = "../../utils/zerovec" }
zerovec-derive = { path = "../../utils/zerovec/derive" }
bies = { path = "../../experimental/bies" }
ixdtf = { path = "../../experimental/ixdtf" }
zerotrie = { path = "../../experimental/zerotrie" }

icu_benchmark_macros = { path = "../../tools/benchmark/macros" }
