[package]
name = "icu-utils-num"
description = "Low-level tools for dealing with numbers"
version = "0.0.1"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]

[dependencies]
smallvec = "1.4"
static_assertions = "1.1"

[dev-dependencies]
rand = "0.7"
criterion = "0.3.3"
rand_pcg = "0.2"
rand_distr = "0.2"

[lib]
bench = false

[[bench]]
name = "fixed_decimal"
harness = false
