# This file is part of ICU4X.
#
# This file is licensed under the Apache License, Version 2.0,
# which can be found in the LICENSE file in the
# calendrical_calculations package root or online at
# <https://www.apache.org/licenses/LICENSE-2.0>.

[package]
name = "calendrical_calculations"
description = "Calendrical calculations in Rust"
version = "0.1.0"
categories = ["rust-patterns", "memory-management", "caching", "no-std", "data-structures"]
keywords = ["zerocopy", "serialization", "zero-copy", "serde"]

authors.workspace = true
edition.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true


# This is a special exception: The algorithms in this crate are based on "Calendrical Calculations" by Reingold and Dershowitz
# which has its lisp code published at https://github.com/EdReingold/calendar-code2/
license = "Apache-2.0"

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true



[dependencies]
[dev-dependencies]


[package.metadata.cargo-all-features]
# Bench feature gets tested separately and is only relevant for CI
denylist = ["bench"]
