# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

##########################################
# PLEASE KEEP THIS IN SYNC WITH cargo.md #
##########################################

[package]
name = "demo_experimental"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
icu = { version = "1.1", features = ["icu_segmenter"] }
icu_testdata = { version = "1.1", features = ["icu_segmenter"] }
