# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_harfbuzz"
description = "HarfBuzz glue code for ICU4X"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
# Omit most optional dependency features from permutation testing
skip_optional_dependencies = true
# Bench feature gets tested separately and is only relevant for CI.
# logging enables a feature of a dependency that has no externally visible API changes
# serde enables dependency features but buffer_provider affects the actual code
denylist = ["bench", "serde", "logging"]

[dependencies]
harfbuzz-sys = { version = "0.5.0" }
icu_normalizer = { workspace = true }
icu_properties = { workspace = true }
icu_provider = {workspace = true, features = ["macros"] }
displaydoc = { version = "0.2.3", default-features = false }
tinystr = { workspace = true }

[dev-dependencies]
harfbuzz = { version = "0.4.0" }

[features]
default = []
compiled_data = ["icu_normalizer/compiled_data", "icu_properties/compiled_data"]
std = []
serde = ["icu_properties/serde", "icu_normalizer/serde", "icu_provider/serde"]
