# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_codepointtrie_builder"
description = "Runtime builder for CodePointTrie"
version = "0.3.5"
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "list_to_ucptrie.wasm"
]

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[features]
# Use the wasm builder
default = ["wasm"]
wasm = ["wasmer", "wasmer-wasi", "once_cell"]
# Use the ICU4C builder
# needs the ICU4C_LIB_PATH variable set and pointing to an ICU4C lib folder
# containing dylibs. If you want to use staticlibs, set ICU4C_LINK_STATICALLY.
# Will be silently disabled if the wasm feature is enabled
icu4c = ["zerovec"]

[dependencies]
icu_collections = { workspace = true, features = ["serde"] }
once_cell = { version = "1.18.0", optional = true }
toml = "0.5"
zerovec = { workspace = true, optional = true }

[dependencies.wasmer]
version = "2.2.1"
default-features = false
optional = true
features = [
    # We are running on the local system (as opposed to JavaScript)
    "sys",
    # By default, use the Singlepass compiler for faster startup time
    "default-singlepass",
    # By default, use the Universal engine for in-memory compiled code
    "default-universal"
]

[dependencies.wasmer-wasi]
version = "2.2.1"
default-features = false
optional = true
features = [
    # We are running on the local system (as opposed to JavaScript)
    "sys",
    # We don't need real filesystem access, so use mem-fs
    "mem-fs"
]

[dev-dependencies]
icu = { workspace = true }

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
# these need env vars. They still get `cargo check'd` when doing `--all-features`
denylist = ["icu4c"]
