# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_codepointtrie_builder"
description = "Runtime builder for CodePointTrie"
version = "0.3.8"
license = "Unicode-3.0"
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "ucptrie_wrap.wasm"
]

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[features]
# Use the wasm builder
default = ["wasm"]
wasm = ["dep:wasmi", "dep:wat"]
# Use the ICU4C builder
# needs the ICU4C_LIB_PATH variable set and pointing to an ICU4C lib folder
# containing dylibs. If you want to use staticlibs, set ICU4C_LINK_STATICALLY.
# Will be silently disabled if the wasm feature is enabled
icu4c = []

[dependencies]
icu_collections = { workspace = true, features = ["serde"] }
zerovec = { workspace = true }
wasmi = { workspace = true, optional = true }
wat = { workspace = true, optional = true }

[dev-dependencies]
icu = { path = "../../icu" }

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
# these need env vars. They still get `cargo check'd` when doing `--all-features`
denylist = ["icu4c"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(icu4c_enable_renaming)'] }