# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_provider_fs"
description = "ICU4X data provider that reads from structured data files"
version = "0.1.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "Cargo.toml",
    "README.md"
]

[package.metadata.cargo-all-features]
# Skip combinations of export with bincode, since they are designed to fail
skip_feature_sets = [
    ["export", "bincode"],
    ["export-bin", "bincode"],
]
# Omit most optional dependency features from permutation testing
skip_optional_dependencies = true
extra_features = [
    "log",
]

[dependencies]
icu_provider = { version = "0.1", path = "../provider", features = ["provider_serde"] }
icu_locid = { version = "0.1", path = "../locid", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
erased-serde = { version = "0.3" }

# Serializers
# Note: serde_json is always included because it is used for parsing manifest.json
serde_json = { version = "1.0" }
bincode = { version = "1.3", optional = true }

# Dependencies for the export module
log = { version = "0.4", optional = true }
static_assertions = { version = "1.1", optional = true }

# Dependencies for the binary
clap = { version = "2.33", optional = true }
icu_provider_cldr = { version = "0.1", path = "../provider_cldr", features = ["download"], optional = true }
simple_logger = { version = "1.11", optional = true }

[dev-dependencies]
icu_benchmark_macros = { version = "0.1", path = "../../tools/benchmark/macros" }
icu_locid_macros = { version = "0.1", path = "../locid/macros" }
icu_plurals = { version = "0.1", path = "../plurals" }
criterion = "0.3.3"

[features]
export = ["static_assertions", "log"]
export-bin = ["export", "clap", "icu_provider_cldr", "simple_logger"]
bench = []

[[bin]]
name = "icu4x-cldr-export"
required-features = [ "export-bin" ]

[[bench]]
name = "provider_fs"
harness = false
