# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[alias]

### INDIVIDUAL TEST AND LINT TASKS ###

# Build and run all code paths except docs
test-all = "make test-all-features"

# Build and run all docs tests
test-docs = "make test-docs"

# Build and run docs tests with default features
test-docs-defaults = "make test-docs-defaults"

# Check for formatting on all code
fmt-check = "make fmt-check"

# Run Clippy on all code paths
# Keep args in sync with `clippy` job in .github/workflows/build-test.yml
# unknown-clippy-lints: to allow us to work with nightly clippy lints that we don't CI
# field-reassign-with-default: https://github.com/rust-lang/rust-clippy/issues/6559 (fixed in nightly but not stable)
clippy-all = "clippy --all-features --all-targets -- -D warnings -Aclippy::field-reassign-with-default"

### META TASKS ###

# Run quick version of all lints and tests
quick = "make quick"

# Run all lints and tests
ci = "make ci"

tidy = "make tidy"

### WASM TASKS ###

# Re-build standard library with panic=abort.
wasm-build-dev = "build -Z build-std=std,panic_abort --target wasm32-unknown-unknown"
wasm-build-release = "build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target wasm32-unknown-unknown --release"

[target.wasm32-unknown-unknown]
rustflags = [
  # 10 KiB heap size, to fit in 1 page.
  "-C", "link-args=-z stack-size=10240",
  # Several options to reduce code size.
  "-C", "panic=abort",
  "-C", "opt-level=s",
]
