# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

##########################################
# PLEASE KEEP THIS IN SYNC WITH cargo.md #
##########################################

[package]
name = "tutorial_baked"
edition = "2021"
publish = false

[dependencies]
icu = { version = "1.5", default-features = false } # turn off compiled_data
icu_provider = "1.5" # for databake
icu_provider_baked = "1.5" # for databake
zerovec = "0.10" # for databake

[build-dependencies]
icu = "1.5"
icu_datagen = "1.5"
icu_datagen_bikeshed = "1.5"
