# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "crate"
publish = false
version = "0.0.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
icu_capi = { version = "1.4", default-features = false, features = ["compiled_data", "icu_decimal"] }
dlmalloc = { version = "0.2", features = ["global"] }

[features]
std = []
