# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

lib-name = "icu"

[demo-gen]
module-name = "icu"

[cpp]
# lib-name becomes a namespace, we don't want to clash
# with ICU4C
lib-name = "icu4x"

[kotlin]
domain = "org.unicode"
# org.unicode.icu is ICU4J
lib-name = "icu4x"
