# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "codegen"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
askama = { workspace = true }
icu = { workspace = true, features = ["compiled_data"] }
heck = "0.4"

[package.metadata.cargo-all-features]
# Unpublished internal tool; skip
skip_package = true
