# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_capi_gn"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
# Note: Only dependencies that are explicitly listed here are given public GN build targets.
icu_capi = { version = "1.0", path = "../../ffi/diplomat", default-features = false, features = ["default_components"] }
icu = { version = "1.0", path = "../../components/icu", default-features = false }
icu_provider = { version = "1.0", path = "../../provider/core" }

# TODO: Determine the correct rustflags for memchr
[gn.package.memchr."2.5.0"]
rustflags = []

[gn.package.proc-macro2."1.0.63"]
rustflags = ["--cfg=use_proc_macro", "--cfg=wrap_proc_macro", "--cfg=proc_macro_span"]

[gn.package.quote."1.0.26"]
rustflags = []

[gn.package.serde."1.0.160"]
rustflags = []

[gn.package.serde_derive."1.0.160"]
rustflags = []

[gn.package.libm."0.2.6"]

# Build cargo-gnaw with the checked-in lockfile
[workspace]
members = ["third_party_tools/fuchsia/tools/cargo-gnaw"]
