# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_capi_gn"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
# Note: Only dependencies that are explicitly listed here are given public GN build targets.
icu_capi = { version = "1.0", path = "../../ffi/diplomat", default-features = false, features = ["default_components", "provider_test", "any_provider"] }
icu = { version = "1.0", path = "../../components/icu" }
icu_provider = { version = "1.0", path = "../../provider/core" }

[gn.package.log."0.4.14"]
rustflags = ["--cfg=atomic_cas", "--cfg=has_atomics"]

# TODO: Determine the correct rustflags for memchr
[gn.package.memchr."2.5.0"]
rustflags = []

[gn.package.proc-macro2."1.0.32"]
rustflags = ["--cfg=lexerror_display", "--cfg=hygiene", "--cfg=literal_from_str", "--cfg=is_available", "--cfg=use_proc_macro", "--cfg=wrap_proc_macro", "--cfg=proc_macro_span"]

[gn.package.ryu."1.0.5"]
rustflags = ["--cfg=integer128", "--cfg=maybe_uninit"]

[gn.package.serde."1.0.130"]
rustflags = ["--cfg=ops_bound", "--cfg=core_reverse", "--cfg=de_boxed_c_str", "--cfg=de_boxed_path", "--cfg=de_rc_dst", "--cfg=core_duration", "--cfg=integer128", "--cfg=range_inclusive", "--cfg=iterator_try_fold", "--cfg=num_nonzero", "--cfg=serde_derive", "--cfg=core_try_from", "--cfg=num_nonzero_signed", "--cfg=systemtime_checked_add", "--cfg=std_atomic64", "--cfg=std_atomic"]

[gn.package.serde_derive."1.0.130"]
rustflags = ["--cfg=underscore_consts", "--cfg=ptr_addr_of"]

[gn.package.syn."1.0.81"]
rustflags = []

[gn.package.num-traits."0.2.15"]
rustflags = ["--cfg=has_i128"]

[gn.package.libm."0.2.6"]
rustflags = []

# Build cargo-gnaw with the checked-in lockfile
[workspace]
members = ["third_party_tools/fuchsia/tools/cargo-gnaw"]
