# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_singlenumberformatter"
version = "0.0.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
fixed_decimal = { workspace = true }
icu_provider = { workspace = true, features = ["macros"] }
icu_locid = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }
displaydoc = { version = "0.2.3", default-features = false }
zerovec = { workspace = true, features = ["yoke"] }
databake = { workspace = true, optional = true, features = ["derive"]}
tinystr = { workspace = true, features = ["zerovec"], default-features = false }


[features]
default = []
serde = ["dep:serde", "zerovec/serde", "icu_locid/serde", "icu_provider/serde"]
datagen = ["serde", "zerovec/databake", "databake", "tinystr/databake"]

