# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "tzif"
description = "A parser for TZif files"
version = "0.4.0"
keywords = ["time-zone", "posix", "iana", "parse", "data"]
categories = ["date-and-time", "parser-implementations"]

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version = "1.82"

[package.metadata.workspaces]
independent = true

[dependencies]
combine = { workspace = true }

[dev-dependencies]
walkdir = { workspace = true }
