# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "tzif"
rust-version = "1.61.0"
authors = ["The ICU4X Project Developers"]
description = "A parser for TZif files"
version = "0.2.1"
edition = "2021"
readme = "README.md"
license = "Unicode-DFS-2016"
repository = "https://github.com/unicode-org/icu4x"
keywords = ["time-zone", "posix", "iana", "parse", "data"]
categories = ["date-and-time", "parser-implementations"]

[package.metadata.workspaces]
independent = true

[dependencies]
combine = "4.6.4"

[dev-dependencies]
walkdir = "2.3.2"
