# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
[package]
name = "icu_locid_macros"
description = "proc-macros for icu_locid"
version = "0.1.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "Cargo.toml",
    "README.md"
]

[lib]
proc_macro = true

[dependencies]
proc-macro-crate = "0.1.5"
icu_locid = { version = "0.1", path = "../" }
tinystr = "0.4"
