# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

##########################################
# PLEASE KEEP THIS IN SYNC WITH cargo.md #
##########################################

[package]
name = "datetime_cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
icu = { version = "1.3", features = ["serde", "logging"] }
icu_provider_blob = "1.3"
time = { version = "0.3", features = ["local-offset"] }
