# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_collator_data"
description = "Data for the icu_collator crate"
license-file = "LICENSE"
version = "1.4.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.sources]
cldr = { tagged = "44.0.0" }
icuexport = { tagged = "release-74-1" }
segmenter_lstm = { tagged = "v0.1.0" }